parameters:

services:
    star_rating.type:
        class: Brokoskokoli\StarRatingBundle\Form\RatingType
        tags:
            - { name: form.type, alias: rating }

    star_rating.twig:
        class: Brokoskokoli\StarRatingBundle\Extensions\StarRatingExtension
        tags: [{ name: twig.extension }]
        arguments:
            - '@service_container'
